name: Cron-staging
on:
  schedule:
    - cron: "0 4 * * *"
jobs:
  experiment-integration:
    name: experiment-integration
    runs-on: macOS-latest
    env:
      QISKIT_IBM_STAGING_API_TOKEN: ${{ secrets.QISKIT_IBM_STAGING_API_TOKEN }}
      QISKIT_IBM_STAGING_API_URL: ${{ secrets.QISKIT_IBM_STAGING_API_URL }}
      QISKIT_IBM_STAGING_DEVICE: "ibmq_qasm_simulator"
      QISKIT_IBM_USE_STAGING_CREDENTIALS: True
      LOG_LEVEL: DEBUG
      STREAM_LOG: True
      QISKIT_IN_PARALLEL: True
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install Deps
        run: python -m pip install -U tox setuptools virtualenv wheel
      - name: Run Tests
        run: tox -epy38 -- -n test/database_service/test_experiment_data_integration.py
