name: Tests
on:
  push:
    branches: [ 'stable/*' ]
  pull_request:
    branches: [ main, 'stable/*' ]
  merge_group:
    branches: [ main ]
concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  docs:
    name: docs
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-docs-${{ hashFiles('setup.py','requirements.txt','requirements-dev.txt','constraints.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-docs-
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install Deps
        run: |
          python -m pip install -U tox
      - name: Build Docs
        run: git remote add upstream https://github.com/Qiskit/qiskit-experiments
        run: git fetch upstream
        run: tox -edocs
      - name: Compress Artifacts
        run: |
          mkdir artifacts
          tar -Jcvf html_docs.tar.xz docs/_build/html
          mv html_docs.tar.xz artifacts/.
      - uses: actions/upload-artifact@v3
        with:
          name: html_docs
          path: artifacts